#define VERBOSE false

#include "testUtil.h"
#include "testVector.h"

#include "PacketMathOldFun.h"

#include "PacketMathTests/pset1Test.h"
#include "PacketMathTests/pzeroTest.h"
#include "PacketMathTests/ploadTest.h"
#include "PacketMathTests/ploaduTest.h"
#include "PacketMathTests/paddTest.h"
#include "PacketMathTests/psubTest.h"
#include "PacketMathTests/pnegateTest.h"
#include "PacketMathTests/pmulTest.h"
#include "PacketMathTests/pdivTest.h"
#include "PacketMathTests/pset1frombitsTest.h"
#include "PacketMathTests/peven_maskTest.h"
#include "PacketMathTests/pload1Test.h"
#include "PacketMathTests/plsetTest.h"
#include "PacketMathTests/paddsubTest.h"
#include "PacketMathTests/ptrueTest.h"
#include "PacketMathTests/pandTest.h"
#include "PacketMathTests/porTest.h"
#include "PacketMathTests/pxorTest.h"
#include "PacketMathTests/pandnotTest.h"
#include "PacketMathTests/pcmp_leTest.h"
#include "PacketMathTests/pcmp_ltTest.h"
#include "PacketMathTests/pcmp_eqTest.h"
#include "PacketMathTests/pcmp_lt_or_nanTest.h"
#include "PacketMathTests/pminTest.h"
#include "PacketMathTests/pmaxTest.h"
#include "PacketMathTests/parithmetic_shift_rightTest.h"
#include "PacketMathTests/plogical_shift_rightTest.h"
#include "PacketMathTests/plogical_shift_leftTest.h"
#include "PacketMathTests/pabsTest.h"
#include "PacketMathTests/proundTest.h"
#include "PacketMathTests/printTest.h"
#include "PacketMathTests/pceilTest.h"
#include "PacketMathTests/pfloorTest.h"
#include "PacketMathTests/ploaddupTest.h"
#include "PacketMathTests/ploadquadTest.h"
#include "PacketMathTests/pgatherTest.h"
#include "PacketMathTests/pstoreTest.h"
#include "PacketMathTests/pstoreuTest.h"
#include "PacketMathTests/pscatterTest.h"
#include "PacketMathTests/pstore1Test.h"
#include "PacketMathTests/pfirstTest.h"
#include "PacketMathTests/preverseTest.h"
#include "PacketMathTests/preduxTest.h"
#include "PacketMathTests/pfrexp_generic_get_biased_exponentTest.h"
#include "PacketMathTests/pldexpTest.h"
#include "PacketMathTests/predux_half_dowto4Test.h"
#include "PacketMathTests/predux_mulTest.h"
#include "PacketMathTests/predux_minTest.h"
#include "PacketMathTests/predux_maxTest.h"
#include "PacketMathTests/predux_anyTest.h"
#include "PacketMathTests/pmaddTest.h"
#include "PacketMathTests/pmsubTest.h"
#include "PacketMathTests/pnmaddTest.h"
#include "PacketMathTests/pnmsubTest.h"
#include "PacketMathTests/pselectTest.h"
#include "PacketMathTests/pblendTest.h"
#include "PacketMathTests/padd_maskTest.h"
#include "PacketMathTests/ploadu_maskTest.h"

int main() { executeTest(); }
